#==========================  Modules configuration ============================
auditbeat.modules:

- module: file_integrity
  paths:
  - /home/vagrant/

- module: auditd
  backlog_limit: 8196
  include_raw_message: true
  include_warnings: true

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  hosts: ["localhost:9200"]

#============================== Kibana =====================================

setup.kibana:
  host: "localhost:5601"

setup.dashboards.enabled: true

#============================== Xpack Monitoring =====================================

xpack.monitoring.enabled: true
