#==========================  Modules configuration ============================
auditbeat.modules:

- module: file_integrity
  paths:
  - /home/vagrant/
  max_file_size: 100 MiB
  hash_types: [sha1]


- module: auditd
  resolve_ids: true
  failure_mode: silent
  backlog_limit: 8196
  rate_limit: 0
  include_raw_message: true
  include_warnings: true

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  hosts: ["localhost:9200"]

#============================== Kibana =====================================

setup.kibana:
  host: "localhost:5601"

setup.dashboards.enabled: true

#============================== Xpack Monitoring =====================================

xpack.monitoring.enabled: true
