#==========================  Modules configuration ============================
filebeat.modules:

#------------------------------- System Module -------------------------------
- module: system
#------------------------------- Auditd Module -------------------------------
- module: auditd
#------------------------------ logstash Module ------------------------------
- module: logstash
#------------------------------- mongodb Module ------------------------------
- module: mongodb
#-------------------------------- Nginx Module -------------------------------
- module: nginx
#-------------------------------- Redis Module -------------------------------
- module: redis


#=========================== Filebeat inputs =============================

# List of inputs to fetch data.
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/kibana/kibana.log
  json.message_key: log
#  fields:
#    type: kibana

# filebeat.autodiscover:
#   # List of enabled autodiscover providers
#   providers:
#     - type: docker
#       templates:
#         - condition:
#             equals.docker.container.image: busybox
#           config:
#             - type: log
#               paths:
#                 - /var/lib/docker/containers/${data.docker.container.id}/*.log

processors:
#- add_docker_metadata: ~
- add_host_metadata: ~

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  enabled: true
  hosts: ["localhost:9200"]

#----------------------------- Logstash output ---------------------------------
output.logstash:
  enabled: false
  hosts: ["localhost:5044"]

#============================== Kibana =====================================

setup.kibana:
  host: "localhost:5601"

setup.dashboards.enabled: true

#============================== Xpack Monitoring =====================================

xpack.monitoring.enabled: true

