############################# Heartbeat ######################################

# Configure monitors
heartbeat.monitors:
- type: http
  schedule: '@every 10s'
  urls: ["http://localhost:80"]
  check.response:
    status: 200

#================================ Processors ===================================

processors:
- add_docker_metadata: ~
- add_host_metadata: ~

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  hosts: ["localhost:9200"]

#----------------------------- Logstash output ---------------------------------
output.logstash:
  enabled: false
  hosts: ["localhost:5044"]

#============================== Kibana =====================================

setup.kibana:
  host: "localhost:5601"

setup.dashboards.enabled: true

#============================== Xpack Monitoring =====================================

xpack.monitoring.enabled: true

